import Head from "next/head";

import { Inter, Island_Moments } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });
import { useEffect, useState } from "react";
import {
  Container,
  Stack,
  Input,
  Checkbox,
  Text,
  List,
  ListItem,
  Button,
  SimpleGrid,
  Flex,
  Box,
  Modal,
  ModalOverlay,
  ModalHeader,
  ModalBody,
  ModalContent,
  ModalCloseButton,
  useDisclosure,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import PokemonCard from "@/components/PokemonCard";
import PokemonData from "@/components/PokemonData";

export default function Home() {
  const pokemonDataModal = useDisclosure();

  const [isLoading, setIsLoading] = useState(false);
  const [pokemon, setPokemon] = useState([]);
  const [selectedPokemon, setSelectedPokemon] = useState();
  const [totalPokemon, setTotalPokemon] = useState(0);
  const [offset, setOffset] = useState(0);
  const [isLoadMore, setIsLoadMore] = useState(true);
  const [checkAll, setCheckAll] = useState(true);
  const [checkCatched, setCheckCatched] = useState(false);

  useEffect(() => {
    fetchPokemon(offset);
  }, [offset]);

  // Función para obtener los Pokémon desde la API
  const fetchPokemon = async (offset) => {
    setIsLoading(true);
    try {
      const response = await axios.get(
        `https://pokeapi.co/api/v2/pokemon/?limit=20&offset=${offset}`
      );
      const promises = response.data.results.map((result) => axios(result.url));
      const fetchedPokemon = (await Promise.all(promises)).map(
        (res) => res.data
      );
      setPokemon(fetchedPokemon);
      setTotalPokemon(response.data.count);
    } catch (error) {
      console.error("Error fetching Pokémon:", error);
    }
    setIsLoading(false);
  };

  function getCatched(filter) {
    setIsLoading(true);

    if (checkCatched || filter === "catched") {
      const fetchCatched = async () => {
        try {
          const response = await axios.get(`/api/catched`);
          setPokemon(response.data);
        } catch (error) {
          console.error("Error:", error);
        }
      };
      fetchCatched();
    } else {
      fetchPokemon(offset);
    }
    setIsLoading(false);
  }

  // Paginación
  function handleNextPage() {
    if (totalPokemon - offset > 20 && checkAll) {
      setOffset(offset + 20);
      setIsLoadMore(true);
    }
  }

  function handlePreviousPage() {
    if (offset >= 20 && checkAll) {
      setOffset(offset - 20);
      setIsLoadMore(false);
    }
  }

  function handleViewPokemon(pokemon) {
    setSelectedPokemon(pokemon);
    pokemonDataModal.onOpen();
  }

  function handleFilterChange(filter) {
    if (filter === "catched") {
      setCheckCatched(true);
      setCheckAll(false);
      getCatched(filter);
    } else {
      setCheckAll(true);
      setCheckCatched(false);
      fetchPokemon(offset);
    }
  }

  return (
    <>
      <Head>
        <title>Pokemon Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex minH="100vh" justifyContent="center">
        <Container maxW="container.lg">
          <Stack direction="row" pt="7" px="16" spacing="8">
            <Checkbox
              isChecked={checkAll}
              onChange={() => handleFilterChange("all")}
            >
              All Pokemons
            </Checkbox>
            <Checkbox
              isChecked={checkCatched}
              onChange={() => handleFilterChange("catched")}
            >
              Catched Pokemons
            </Checkbox>
          </Stack>
          <Stack p="5" alignItems="center" spacing="5">
            <SimpleGrid spacing="5" columns={{ base: 1, md: 5 }}>
              {pokemon.map((pokemon) => (
                <Box
                  as="button"
                  key={pokemon.id}
                  onClick={() => handleViewPokemon(pokemon)}
                >
                  <PokemonCard pokemon={pokemon} />
                </Box>
              ))}
            </SimpleGrid>
            <Stack display={checkAll ? "flex" : "none"} direction="row">
              <Button
                display={offset < 20 ? "none" : "flex"}
                isLoading={isLoading && !isLoadMore}
                onClick={handlePreviousPage}
                loadingText="Cargando..."
                colorScheme="teal"
                variant="outline"
              >
                Ver anteriores
              </Button>
              <Button
                display={totalPokemon - offset > 20 ? "flex" : "none"}
                isLoading={isLoading && isLoadMore}
                onClick={handleNextPage}
                loadingText="Cargando..."
                colorScheme="teal"
                variant="outline"
              >
                Cargas más
              </Button>
            </Stack>
            <Stack
              display={checkCatched && pokemon.length === 0 ? "flex" : "none"}
            >
              <Text>No hay pokemones capturados</Text>
            </Stack>
          </Stack>
        </Container>
      </Flex>
      <Modal {...pokemonDataModal} onCloseComplete={getCatched}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader textTransform="capitalize">
            {selectedPokemon?.name}
          </ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            {selectedPokemon && <PokemonData pokemon={selectedPokemon} />}
          </ModalBody>
        </ModalContent>
      </Modal>
    </>
  );
}
